# Food Embedding Testing Notebook

This notebook checks that the functionality of the `FoodEmbedding` is working as expected.

In [2]:
import sys
sys.path.append("..")

from FoodEmbedding import FoodEmbedding
import os

In [3]:
embedding = FoodEmbedding()

c:\Users\micha\Documents\School\University\3rd Year\Final Year Project\Code\food_data_extraction\FoodEmbedding.py:19: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  self.food_nutrient = pd.read_csv(f"{os.path.join(self.base_dir, 'FoodData_Central_csv_2025-12-18')}/food_nutrient.csv")

In [4]:
if os.path.exists("food_embedding.faiss"):
    embedding.load(index_path = "food_embedding.faiss")
else:
    embedding.initialise()
    embedding.save()

In [5]:
result = embedding.search("black pepper")

In [6]:
result

,fdc_id,data_type,description,food_category_id,publication_date,score
1522012,2157235,branded_food,BLACK PEPPER,Herbs & Spices,2021-10-28,1.0
1136300,1721294,branded_food,BLACK PEPPER,Herbs & Spices,2021-03-19,1.0
853546,1428997,branded_food,BLACK PEPPER,Herbs & Spices,2021-02-26,1.0
515960,1039497,branded_food,BLACK PEPPER,Herbs & Spices,2020-06-26,1.0
473147,946040,branded_food,BLACK PEPPER,Herbs & Spices,2020-05-28,1.0

In [7]:
first_id = result ["fdc_id"].iloc [0]

In [8]:
nutritional_info = embedding.get_nutritional_information(first_id)

In [9]:
nutritional_info

    nutrient_id  amount unit_name                            name
0          1162    0.00        MG  Vitamin C, total ascorbic acid
1          1258    0.00         G    Fatty acids, total saturated
2          1104    0.00        IU                   Vitamin A, IU
3          1253    0.00        MG                     Cholesterol
4          1257    0.00         G        Fatty acids, total trans
5          1004    0.00         G               Total lipid (fat)
6          1008    0.00      KCAL                          Energy
7          1089    0.00        MG                        Iron, Fe
8          1087    0.00        MG                     Calcium, Ca
9          1093    0.00        MG                      Sodium, Na
10         1079   41.70         G            Fiber, total dietary
11         2000    0.00         G                    Total Sugars
12         1003    0.00         G                         Protein
13         1005  166.67         G     Carbohydrate, by difference

In [10]:
portion = embedding.get_portion_size(first_id)

In [11]:
portion

Empty DataFrame
Columns: [id, fdc_id, seq_num, amount, measure_unit_id, portion_description, modifier, gram_weight, data_points, footnote, min_year_acquired]
Index: []

In [12]:
print(first_id)

2157235