# Food Embedding Testing Notebook

This notebook checks that the functionality of the `FoodEmbedding` is working as expected.

Furthermore, the `food_embedding.faiss` file is created in this notebook, which can be used in other places.

In [1]:
import os
import sys

sys.path.append("..")

from FoodEmbedding import FoodEmbedding

In [2]:
embedding = FoodEmbedding()

c:\Users\micha\Documents\School\University\3rd Year\Final Year Project\Code\food_data_extraction\FoodEmbedding.py:35: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  self.food_nutrient = pd.read_csv(

In [3]:
if os.path.exists("food_embedding.faiss"):
    embedding.load(index_path="food_embedding.faiss")
else:
    embedding.initialise()
    embedding.save()

In [13]:
result = embedding.search("onion", top_n=5)

In [14]:
result

,fdc_id,data_type,description,food_category_id,publication_date,score
35373,170000,sr_legacy_food,"Onions, raw",11,2019-04-01,0.723037
1773446,2438059,branded_food,ONION,Breads & Buns,2022-12-22,1.000000
1027402,1605660,branded_food,ONION,Breads & Buns,2021-03-19,1.000000
744749,1313543,branded_food,ONION,Breads & Buns,2021-02-26,1.000000
791002,1364112,branded_food,ONION,Other Cooking Sauces,2021-02-26,1.000000

In [15]:
first_id = result["fdc_id"].iloc[0]

In [16]:
nutritional_info = embedding.get_nutritional_information(first_id)

In [17]:
nutritional_info

     nutrient_id  amount unit_name                      name
0           1106   0.000        UG            Vitamin A, RAE
1           1257   0.000         G  Fatty acids, total trans
2           1104   2.000        IU             Vitamin A, IU
3           1178   0.000        UG              Vitamin B-12
4           1253   0.000        MG               Cholesterol
..           ...     ...       ...                       ...
113         1129   0.000        MG         Tocotrienol, beta
114         1325   0.000         G                 PUFA 20:3
115         1266   0.004         G                  SFA 18:0
116         1213   0.025         G                   Leucine
117         1198   0.100        MG                   Betaine

[118 rows x 4 columns]

In [18]:
portion = embedding.get_portion_size(first_id)

In [19]:
portion

,id,fdc_id,seq_num,amount,measure_unit_id,portion_description,modifier,gram_weight,data_points,footnote,min_year_acquired
4306,85855,170000.0,1.0,1.0,9999.0,NaN,"cup, chopped",160.0,NaN,NaN,NaN
4307,85856,170000.0,2.0,1.0,9999.0,NaN,"cup, sliced",115.0,NaN,NaN,NaN
4308,85857,170000.0,3.0,1.0,9999.0,NaN,tbsp chopped,10.0,NaN,NaN,NaN
4309,85858,170000.0,4.0,1.0,9999.0,NaN,large,150.0,NaN,NaN,NaN
4310,85859,170000.0,5.0,1.0,9999.0,NaN,"slice, large (1/4"" thick)",38.0,NaN,NaN,NaN
4311,85860,170000.0,6.0,1.0,9999.0,NaN,"medium (2-1/2"" dia)",110.0,NaN,NaN,NaN
4312,85861,170000.0,7.0,1.0,9999.0,NaN,"slice, medium (1/8"" thick)",14.0,NaN,NaN,NaN
4313,85862,170000.0,8.0,1.0,9999.0,NaN,small,70.0,NaN,NaN,NaN
4314,85863,170000.0,9.0,1.0,9999.0,NaN,"slice, thin",9.0,NaN,NaN,NaN
4315,85864,170000.0,10.0,10.0,9999.0,NaN,rings,60.0,NaN,NaN,NaN

In [20]:
print(first_id)

170000