In [1]:
from FoodEmbedding import FoodEmbedding

embedding = FoodEmbedding()

c:\Users\micha\Documents\School\University\3rd Year\Final Year Project\Code\food_data_extraction\FoodEmbedding.py:24: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  self.food_nutrient = pd.read_csv(f"{os.path.join(base_dir, 'FoodData_Central_csv_2025-12-18')}/food_nutrient.csv")

In [2]:
import os

if os.path.exists("food_embedding.faiss"):
    embedding.load(index_path = "food_embedding.faiss")
else:
    embedding.initialise()
    embedding.save()

In [3]:
result = embedding.search("Bibb lettuce")

In [4]:
result

,fdc_id,data_type,description,food_category_id,publication_date,score
1747470,2411728,branded_food,BABY LETTUCE,Pre-Packaged Fruit & Vegetables,2022-12-22,0.715602
1709395,2373468,branded_food,BABY LETTUCE,Pre-Packaged Fruit & Vegetables,2022-12-07,0.715602
1514984,2150002,branded_food,BABY LETTUCE,Pre-Packaged Fruit & Vegetables,2021-10-28,0.715602
1350179,1977789,branded_food,BABY LETTUCE,Pre-Packaged Fruit & Vegetables,2021-07-29,0.715602
478108,956127,branded_food,JUST LETTUCE,Pre-Packaged Fruit & Vegetables,2020-06-26,0.694133

In [5]:
first_id = result ["fdc_id"].iloc [0]

In [6]:
nutritional_info = embedding.get_nutritional_information(first_id)

In [7]:
nutritional_info

    nutrient_id  amount unit_name                                      name
0          1089    1.20        MG                                  Iron, Fe
1          1005    2.82         G               Carbohydrate, by difference
2          1092  310.00        MG                              Potassium, K
3          1004    0.00         G                         Total lipid (fat)
4          1110    0.00        IU  Vitamin D (D2 + D3), International Units
5          1003    2.82         G                                   Protein
6          1258    0.00         G              Fatty acids, total saturated
7          2000    0.70         G                              Total Sugars
8          1253    0.00        MG                               Cholesterol
9          1093   63.00        MG                                Sodium, Na
10         1257    0.00         G                  Fatty acids, total trans
11         1079    1.40         G                      Fiber, total dietary
12         1008   25.00      KCAL                                    Energy
13         1087   77.00        MG                               Calcium, Ca

In [8]:
result = embedding.search("Black pepper")

In [9]:
result

,fdc_id,data_type,description,food_category_id,publication_date,score
1522012,2157235,branded_food,BLACK PEPPER,Herbs & Spices,2021-10-28,1.0
1136300,1721294,branded_food,BLACK PEPPER,Herbs & Spices,2021-03-19,1.0
853546,1428997,branded_food,BLACK PEPPER,Herbs & Spices,2021-02-26,1.0
515960,1039497,branded_food,BLACK PEPPER,Herbs & Spices,2020-06-26,1.0
473147,946040,branded_food,BLACK PEPPER,Herbs & Spices,2020-05-28,1.0

In [10]:
embedding.save()