# Food Embedding Testing Notebook

This notebook checks that the functionality of the `FoodEmbedding` is working as expected.

In [1]:
import os
import sys

sys.path.append("..")

from FoodEmbedding import FoodEmbedding

In [2]:
embedding = FoodEmbedding()

c:\Users\micha\Documents\School\University\3rd Year\Final Year Project\Code\food_data_extraction\FoodEmbedding.py:34: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  self.food_nutrient = pd.read_csv(

In [3]:
if os.path.exists("food_embedding.faiss"):
    embedding.load(index_path = "food_embedding.faiss")
else:
    embedding.initialise()
    embedding.save()

In [ ]:
result = embedding.search("onions", top_n = 5)

In [9]:
result

,fdc_id,data_type,description,food_category_id,publication_date,score
35373,170000,sr_legacy_food,"Onions, raw",11,2019-04-01,0.809984
35381,170008,sr_legacy_food,"Onions, sweet, raw",11,2019-04-01,0.775475
791002,1364112,branded_food,ONION,Other Cooking Sauces,2021-02-26,0.892297
744749,1313543,branded_food,ONION,Breads & Buns,2021-02-26,0.892297
279128,570221,branded_food,ONION,Other Cooking Sauces,2019-04-01,0.892297
...,...,...,...,...,...,...
1124636,1709461,branded_food,PEARL ONIONS,Frozen Vegetables,2021-03-19,0.789575
1350683,1978302,branded_food,PEARL ONIONS,Frozen Vegetables,2021-07-29,0.789575
1063475,1645910,branded_food,PEARL ONIONS,Frozen Vegetables,2021-03-19,0.789575
2045316,2709953,survey_fndds_food,"Onions, green, cooked",6414,2024-10-31,0.788457
1264082,1889025,branded_food,SALT ONION,"Seasoning Mixes, Salts, Marinades & Tenderizers",2021-07-29,0.787674

In [16]:
first_id = result ["fdc_id"].iloc [0]

In [17]:
nutritional_info = embedding.get_nutritional_information(first_id)

In [18]:
nutritional_info

     nutrient_id  amount unit_name                      name
0           1106   0.000        UG            Vitamin A, RAE
1           1257   0.000         G  Fatty acids, total trans
2           1104   2.000        IU             Vitamin A, IU
3           1178   0.000        UG              Vitamin B-12
4           1253   0.000        MG               Cholesterol
..           ...     ...       ...                       ...
113         1129   0.000        MG         Tocotrienol, beta
114         1325   0.000         G                 PUFA 20:3
115         1266   0.004         G                  SFA 18:0
116         1213   0.025         G                   Leucine
117         1198   0.100        MG                   Betaine

[118 rows x 4 columns]

In [9]:
portion = embedding.get_portion_size(first_id)

In [10]:
portion

Empty DataFrame
Columns: [id, fdc_id, seq_num, amount, measure_unit_id, portion_description, modifier, gram_weight, data_points, footnote, min_year_acquired]
Index: []

In [11]:
print(first_id)

170931